# Generated by Django 3.0.5 on 2020-04-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteback', '0005_auto_20200423_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='founder',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='websiteback.Project'),
        ),
    ]
