# Generated by Django 3.0.5 on 2020-04-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteback', '0006_auto_20200423_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
