# Generated by Django 3.0.5 on 2020-04-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteback', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='Без Названия', max_length=120),
        ),
    ]
