# Generated by Django 3.0.5 on 2020-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteback', '0009_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
