# Generated by Django 3.0.5 on 2020-04-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteback', '0011_developer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
